### PR TITLE
Upgrade to 2.1.0.

### LINKED ISSUE #15: Big error onQuit()
Error log:
[Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "ScoreboardsPE/src/Miste/scoreboardspe/API/ScoreboardStore" at line 194
[Server thread/DEBUG]: #0 ScoreboardsPE/src/Miste/scoreboardspe/API/ScoreboardStore(194): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string Invalid argument supplied for foreach(), string PocketMine\plugins\ScoreboardsPE\src\Miste\scoreboardspe\API\ScoreboardStore.php, integer 194, array Array())
[Server thread/DEBUG]: #1 ScoreboardsPE/src/Miste/scoreboardspe/EventHandler(25): Miste\scoreboardspe\API\ScoreboardStore->removePotentialViewer(string KielKing)
[Server thread/DEBUG]: #2 src/pocketmine/plugin/MethodEventExecutor(38): Miste\scoreboardspe\EventHandler->onQuitEvent(pocketmine\event\player\PlayerQuitEvent object)

client crashes after the first time they quit after the time server restarts because of this error

### PR DESCRIPTION
**Pull request by ghost**
* Designed the code :expressionless:
* Fixed known bugs. Closes #15, #17, #18, #19, #20 

**Tested on latest release PocketMine-MP 3.6.3**
Screenshot

### CODE REVIEW

**Review by jasonw4331 — CHANGES_REQUESTED** [review]
The only thing this PR does is add a large amount of PHPdoc comments and fix 3 typos.

There is no reason to bump the plugin version.

**Comment by ghost** [comment]
> The only thing this PR does is add a large amount of PHPdoc comments and fix 3 typos.
> 
> There is no reason to bump the plugin version.

These typos ruined the plug-in's performance.

**Comment by jasonw4331** [comment]
Only the typo [here](https://github.com/MisteFr/ScoreboardsPE/pull/21/files#diff-cdb430ba089dfac2f8ad80fca195e5ecL135) actually affects the code. The unnecessary code [here](https://github.com/MisteFr/ScoreboardsPE/pull/21/files#diff-cdb430ba089dfac2f8ad80fca195e5ecL114) shouldn't actually affect the program since `$pk` is not a variable here. Everything else in this pr appears to be cosmetic.

Also, this pull request only resolves #18, #19, #20 
#15 and #17 originate from different causes.

**Comment by ghost** [comment]
> Only the typo [here](https://github.com/MisteFr/ScoreboardsPE/pull/21/files#diff-cdb430ba089dfac2f8ad80fca195e5ecL135) actually affects the code. The unnecessary code [here](https://github.com/MisteFr/ScoreboardsPE/pull/21/files#diff-cdb430ba089dfac2f8ad80fca195e5ecL114) shouldn't actually affect the program since `$pk` is not a variable here. Everything else in this pr appears to be cosmetic.
> 
> Also, this pull request only resolves #18, #19, #20
> #15 and #17 originate from different causes.

What is wrong with cosmetic change? Is the plugin worse off?

**Comment by MisteFr** [comment]
Thanks for the bug fix.
I will take your changes in another commit as I don't want to bump the version.

**Pull request closed without merging**
